language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jesterhead101/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true jesterhead101/docker-react npm run test

deploy:
  provider: azure_web_apps
  username: ksriharsha@itssglobal.com
  password: Changeit@1.
  site: https://dockerreacthk.azurewebsites.net