sudo: required
language: generic
services:
  - docker 

before_install:
  - docker build -t jesterhead101/docker-react -f Dockerfile.dev .
  
  script:
    - docker run -e CI=true jesterhead101/docker-react npm run test
    
    