version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'

deploy:
  provider: azure_web_apps
  username: ksriharsha@itssglobal.com
  password: Changeit@1.
  site: https://dockerreact1.azurewebsites.net